package raf.dsw.classycraft.app.messagegen;

public enum Event {
    NODE_CANNOT_BE_DELETED, NAME_CANNOT_BE_EMPTY, CANNOT_ADD_CHILD_TO_LEAF,
    PARENT_NOT_SELECTED, NODE_NOT_SELECTED, AUTHOR_MUST_BE_A_PROJECT
    //PROBA
}
