package raf.dsw.classycraft.app.messagegen;

public enum Event {
    NODE_CANNOT_BE_DELETED, NAME_CANNOT_BE_EMPTY, CANNOT_ADD_CHILD_TO_LEAF, PARENT_NOT_SELECTED,
    NODE_NOT_SELECTED, AUTHOR_MUST_BE_A_PROJECT, OPTION_NOT_SELECTED, NAME_TAKEN,
    USE_SIDE_TOOLBAR_OPTION, CONNECTION_MUST_START_FROM_ENTITY, CONNECTION_MUST_END_IN_ENTITY,
    CLASS_NOT_SELECTED


}
